export { googleLogEvents } from './GoogleEvents';
export { facebookAppEvents } from './FacebookAppEvents';

export {
  APP_OPEN,
  LANGUAGE_SELECTION,
  OTP_VERIFICATION_SUCCESS,
  HOME_SCREEN_VIEWED,
  ADD_CROP,
  CROP_CALENDRA_ENROLLMENT,
  SPRAY_SERVICE_BOOKING_DONE,
  CROP_DOCTOR_IMAGE_UPLOAD,
  CROP_DOCTOR_SUCCESS,
  FARM_AREA_CALCULATOR_MEASUREMENT,
  FARM_LOAN_APPLICATION,
  REFERRAL_CODE_SUBMITTED
} from './EventConstant';
