export const Images = {
  alert: require('../../assets/images/alert.png'),
  profile_image: require('../../assets/images/profile.png'),
  success: require('../../assets/images/Success.png'),
  failure: require('../../assets/images/failure.png'),
  line: require('../../assets/images/line.png'),
  aboutUs: require('../../assets/images/aboutus.jpeg'),
  tcImage: require('../../assets/images/T&CImage.jpeg'),
  nodataImage: require('../../assets/images/nodataimage.png'),
  noStoreImage: require('../../assets/images/Nostore.png'),
  NoProductImage: require('../../assets/images/NoProductsFound.png'),
  homePageBG: require('../../assets/images/HomePage.jpg'),
  myCropBg: require('../../assets/images/MyCropBG.jpeg'),
  CPrecommenderBG: require('../../assets/images/CropProtectionRecommender.jpeg'),
  // Stewarship Guidlines Images
  applyingPesticides1: require('../../assets/images/ApplyingPesticides.png'),
  applyingPesticides2: require('../../assets/images/ApplyingPesticides2.png'),
  applyingPesticides3: require('../../assets/images/ApplyingPesticides3.png'),
  handlePesticides1: require('../../assets/images/HandlingPesticides.png'),
  handlePesticides2: require('../../assets/images/HandlingPesticides2.png'),
  handlePesticides3: require('../../assets/images/HandlingPesticides3.png'),
  // End Stewarship Guidlines Images
  downloadingLoader: require('../../assets/images/DownloadingLoader.gif'),
  transparentLoader: require('../../assets/images/TransparentLoader.gif'),
  emptyStar: require('../../assets/images/emptyStar.png'),
  filledStar: require('../../assets/images/filledStar.png'),
  deliveryInformation: require('../../assets/images/DeliveryInformation.png'),
  creditCard: require('../../assets/images/CreditCard.png'),
  vehicle: require('../../assets/images/Vehicle.png'),
  circleCheck: require('../../assets/images/circleCheck.png'),
  plantixCardImage: require('../../assets/images/plantix_card_image.png'),
  plantixLogo: require('../../assets/images/plantixLogo.png'),
  eCommerceShop: require('../../assets/images/ECommerceShop.png'),
  default_person: require('../../assets/images/default_person.png'),
  dashboardBg: require('../../assets/images/DashboardBg.png'),
  scanProducts: require('../../assets/images/ScanProducts.png'),
  eCommerce: require('../../assets/images/ECommerce.png'),
  eCommerceGrass: require('../../assets/images/grama.png'),
  tick: require('../../assets/images/tick.png'),
  noInternet: require('../../assets/images/noInternet.png'),
  videoPlaceholder: require('../../assets/images/videoPlaceholder.jpeg'),
  cropDownloadBg: require('../../assets/images/cropDownloadBg.png'),
  whatsapp: require('../../assets/images/whatsapp.png'),
  mapViewMarker: require('../../assets/images/Marker.png'),
  referralPlaceholder: require('../../assets/images/referralPlaceholder.png'),
  example1: require('../../assets/images/ex1.jpg'),
  example2: require('../../assets/images/ex2.jpg'),
  VegetableSeeds: require('../../assets/images/VegetableSeeds.png'),
  Rectanglecurve: require('../../assets/images/Rectanglecurve.png'),
  video: require('../../assets/images/Video.png'),
  splash: require('../../assets/images/Splash.jpg'),
  appFeedbackHeader: require('../../assets/images/AppFeedbackHeader.png'),
  // Centrigo Images
  centrigo_logo: require('../../assets/images/centrigo/centrigoLogo.png'),
  centrigo_logo_light: require('../../assets/images/centrigo/centrigoLogoLight.png'),
  toggle_bg: require('../../assets/images/centrigo/BG.png'),
  gradient_bg: require('../../assets/images/centrigo/gradient.png'),
  wrapper_bg_img: require('../../assets/images/centrigo/dash_top_bg.png'),
  slider_gradient: require('../../assets/images/centrigo/cent_slider_gradient.png'),
  cropwise_toggle_bg: require('../../assets/images/centrigo/cropwise_toggle_img.png'),
  centrigo_splash: require('../../assets/images/centrigo/centrigo_splash.png'),
  syn_logo: require('../../assets/images/centrigo/syn_logo.png'),
  bookingToolImage1: require('../../assets/images/BookingToolImage1.png'),
  bookingToolImage2: require('../../assets/images/BookingToolImage2.png'),
  connectionError: require('../../assets/images/centrigo/connectionError.png'),
  successIcon: require('../../assets/images/centrigo/successIcon.png'),
  errorIcon: require('../../assets/images/centrigo/errorIcon.png'),
  // News Feed Section
  videoGroup: require('../../assets/images/video_group.png'),
  youtube: require('../../assets/images/youtube.png'),
  syngentaLogo: require('../../assets/images/syngentaLogo.png'),
  cpGradient: require('../../assets/images/cpGradient.png'),
  playIconBG: require('../../assets/images/VideoFeedIconBG.png'),
  // Refer Earn images
  referEarn: require('../../assets/images/referEarn.png'),
  // New ui Starts
  callSupportNew: require('../../assets/images/callSupportIcon.png'),
  bottomBackgroundNew: require('../../assets/images/Register.png'),
  successNewDesign: require('../../assets/images/SuccessNewDesign.png'),
  // New ui Ends
  // Age Range Images
  firstRange: require('../../assets/images/firstRange.png'),
  secondRange: require('../../assets/images/secondRange.png'),
  thirdRange: require('../../assets/images/thirdRange.png'),
  fourthRange: require('../../assets/images/fourthRange.png'),
  check: require('../../assets/images/check.png')
};
